  $(document).ready(function() {
    var E0at = "FGCU"
    var E0as = "16 "
    var E0bt = "FDU"
    var E0bs = "16 "
    var E11t = "UNC";
    var E11s = "1 ";
    var E116t = "";
    var E116s = "";
    var E28t = "USC";
    var E28s = "8 ";
    var E29t = "Providence";
    var E29s = "9 ";
    var E35t = "Indiana";
    var E35s = "5 ";
    var E312t = "Chattanooga";
    var E312s = "12 ";
    var E44t = "Kentucky";
    var E44s = "4 ";
    var E413t = "Stony Brook";
    var E413s = "13 ";
    var E56t = "Notre Dame";
    var E56s = "6 ";
    var E511at = "Michigan"
    var E511as = "11 "
    var E511bt = "Tulsa"
    var E511bs = "11 "
    var E511t = "";
    var E511s = "";
    var E63t = "West Virginia";
    var E63s = "3 ";
    var E614t = "SFA";
    var E614s = "14 ";
    var E77t = "Wisconsin";
    var E77s = "7 ";
    var E710t = "Pittsburgh";
    var E710s = "10 ";
    var E82t = "Xavier";
    var E82s = "2 ";
    var E815t = "Weber State";
    var E815s = "15 ";
    var E9at = "";
    var E9as = "";
    var E9bt = "";
    var E9bs = "";
    var E10at = "";
    var E10as = "";
    var E10bt = "";
    var E10bs = "";
    var E11at = "";
    var E11as = "";
    var E11bt = "";
    var E11bs = "";
    var E12at = "";
    var E12as = "";
    var E12bt = "";
    var E12bs = "";
    $('#E11t').append(E11t);
    $('#E11s').append(E11s);
    $('#E0at').append(E0at);
    $('#E0as').append(E0as);
    $('#E0bt').append(E0bt);
    $('#E0bs').append(E0bs);
    $('#E28t').append(E28t);
    $('#E28s').append(E28s);
    $('#E29t').append(E29t);
    $('#E29s').append(E29s);
    $('#E35t').append(E35t);
    $('#E35s').append(E35s);
    $('#E312t').append(E312t);
    $('#E312s').append(E312s);
    $('#E44t').append(E44t);
    $('#E44s').append(E44s);
    $('#E413t').append(E413t);
    $('#E413s').append(E413s);
    $('#E56t').append(E56t);
    $('#E56s').append(E56s);
    $('#E511at').append(E511at);
    $('#E511as').append(E511as);
    $('#E511bt').append(E511bt);
    $('#E511bs').append(E511bs);
    $('#E63t').append(E63t);
    $('#E63s').append(E63s);
    $('#E614t').append(E614t);
    $('#E614s').append(E614s);
    $('#E77t').append(E77t);
    $('#E77s').append(E77s);
    $('#E710t').append(E710t);
    $('#E710s').append(E710s);
    $('#E82t').append(E82t);
    $('#E82s').append(E82s);
    $('#E815t').append(E815t);
    $('#E815s').append(E815s);
    $('#E0a').click(function() {
      $('#E116t').empty().append(E0at);
      $('#E116s').empty().append(E0as);
      $('#E9at').empty();
      $('#E9as').empty();
      $('#E13at').empty();
      $('#E13as').empty();
      $('#E15at').empty();
      $('#E15as').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E116t').attr('data-teamname', E0at);
      $('#E116s').attr('data-seed', E0as);
      E116t = E0at;
      E116s = E0as;
    });
    $('#E0b').click(function() {
      $('#E116t').empty().append(E0bt);
      $('#E116s').empty().append(E0bs);
      $('#E9at').empty();
      $('#E9as').empty();
      $('#E13at').empty();
      $('#E13as').empty();
      $('#E15at').empty();
      $('#E15as').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E116t').attr('data-teamname', E0bt);
      $('#E116s').attr('data-seed', E0bs);
      E116t = E0bt;
      E116s = E0bs;
    });
    $('#E11').click(function() {
      $('#E9at').empty().append(E11t);
      $('#E9as').empty().append(E11s);
      $('#E13at').empty();
      $('#E13as').empty();
      $('#E15at').empty();
      $('#E15as').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E9at').attr('data-teamname', E11t);
      $('#E9as').attr('data-seed', E11s);
      E9at = E11t;
      E9as = E11s;
    });
    $('#E116').click(function() {
      $('#E9at').empty().append(E116t);
      $('#E9as').empty().append(E116s);
      $('#E13at').empty();
      $('#E13as').empty();
      $('#E15at').empty();
      $('#E15as').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E9at').attr('data-teamname', E116t);
      $('#E9as').attr('data-seed', E116s);
      E9at = E116t;
      E9as = E116s;
    });
    $('#E28').click(function() {
      $('#E9bt').empty().append(E28t);
      $('#E9bs').empty().append(E28s);
      $('#E13at').empty();
      $('#E13as').empty();
      $('#E15at').empty();
      $('#E15as').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E9bt').attr('data-teamname', E28t);
      $('#E9bs').attr('data-seed', E28s);
      E9bt = E28t;
      E9bs = E28s;
    });
    $('#E29').click(function() {
      $('#E9bt').empty().append(E29t);
      $('#E9bs').empty().append(E29s);
      $('#E13at').empty();
      $('#E13as').empty();
      $('#E15at').empty();
      $('#E15as').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E9bt').attr('data-teamname', E29t);
      $('#E9bs').attr('data-seed', E29s);
      E9bt = E29t;
      E9bs = E29s;
    });
    $('#E35').click(function() {
      $('#E10at').empty().append(E35t);
      $('#E10as').empty().append(E35s);
      $('#E13bt').empty();
      $('#E13bs').empty();
      $('#E15at').empty();
      $('#E15as').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E10at').attr('data-teamname', E35t);
      $('#E10as').attr('data-seed', E35s);
      E10at = E35t;
      E10as = E35s;
    });
    $('#E312').click(function() {
      $('#E10at').empty().append(E312t);
      $('#E10as').empty().append(E312s);
      $('#E13bt').empty();
      $('#E13bs').empty();
      $('#E15at').empty();
      $('#E15as').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E10at').attr('data-teamname', E312t);
      $('#E10as').attr('data-seed', E312s);
      E10at = E312t;
      E10as = E312s;
    });
    $('#E44').click(function() {
      $('#E10bt').empty().append(E44t);
      $('#E10bs').empty().append(E44s);
      $('#E13bt').empty();
      $('#E13bs').empty();
      $('#E15at').empty();
      $('#E15as').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E10bt').attr('data-teamname', E44t);
      $('#E10bs').attr('data-seed', E44s);
      E10bt = E44t;
      E10bs = E44s;
    });
    $('#E413').click(function() {
      $('#E10bt').empty().append(E413t);
      $('#E10bs').empty().append(E413s);
      $('#E13bt').empty();
      $('#E13bs').empty();
      $('#E15at').empty();
      $('#E15as').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E10bt').attr('data-teamname', E413t);
      $('#E10bs').attr('data-seed', E413s);
      E10bt = E413t;
      E10bs = E413s;
    });
        $('#E56').click(function() {
      $('#E11at').empty().append(E56t);
      $('#E11as').empty().append(E56s);
      $('#E14at').empty();
      $('#E14as').empty();
      $('#E15bt').empty();
      $('#E15bs').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E11at').attr('data-teamname', E56t);
      $('#E11as').attr('data-seed', E56s);
      E11at = E56t;
      E11as = E56s;
    });
    $('#E511a').click(function() {
      $('#E511t').empty().append(E511at);
      $('#E511s').empty().append(E511as);
      $('#E11at').empty();
      $('#E11as').empty();
      $('#E13at').empty();
      $('#E13as').empty();
      $('#E15at').empty();
      $('#E15as').empty();
      $('#FF2at').empty();
      $('#FF2as').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E511t').attr('data-teamname', E511at);
      $('#E511s').attr('data-seed', E511as);
      E511t = E511at;
      E511s = E511as;
    });
    $('#E511b').click(function() {
      $('#E511t').empty().append(E511bt);
      $('#E511s').empty().append(E511bs);
      $('#E11at').empty();
      $('#E11as').empty();
      $('#E14at').empty();
      $('#E14as').empty();
      $('#E15bt').empty();
      $('#E15bs').empty();
      $('#FF2at').empty();
      $('#FF2as').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E511t').attr('data-teamname', E511bt);
      $('#E511s').attr('data-seed', E511bs);
      E511t = E511bt;
      E511s = E511bs;
    });
    $('#E511').click(function() {
      $('#E11at').empty().append(E511t);
      $('#E11as').empty().append(E511s);
      $('#E14at').empty();
      $('#E14as').empty();
      $('#E15bt').empty();
      $('#E15bs').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E11at').attr('data-teamname', E511t);
      $('#E11as').attr('data-seed', E511s);
      E11at = E511t;
      E11as = E511s;
    });
    $('#E63').click(function() {
      $('#E11bt').empty().append(E63t);
      $('#E11bs').empty().append(E63s);
      $('#E14at').empty();
      $('#E14as').empty();
      $('#E15bt').empty();
      $('#E15bs').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E11bt').attr('data-teamname', E63t);
      $('#E11bs').attr('data-seed', E63s);
      E11bt = E63t;
      E11bs = E63s;
    });
    $('#E614').click(function() {
      $('#E11bt').empty().append(E614t);
      $('#E11bs').empty().append(E614s);
      $('#E14at').empty();
      $('#E14as').empty();
      $('#E15bt').empty();
      $('#E15bs').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E11bt').attr('data-teamname', E614t);
      $('#E11bs').attr('data-seed', E614s);
      E11bt = E614t;
      E11bs = E614s;
    });
    $('#E77').click(function() {
      $('#E12at').empty().append(E77t);
      $('#E12as').empty().append(E77s);
      $('#E14bt').empty();
      $('#E14bs').empty();
      $('#E15bt').empty();
      $('#E15bs').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E12at').attr('data-teamname', E77t);
      $('#E12as').attr('data-seed', E77s);
      E12at = E77t;
      E12as = E77s;
    });
    $('#E710').click(function() {
      $('#E12at').empty().append(E710t);
      $('#E12as').empty().append(E710s);
      $('#E14bt').empty();
      $('#E14bs').empty();
      $('#E15bt').empty();
      $('#E15bs').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E12at').attr('data-teamname', E710t);
      $('#E12as').attr('data-seed', E710s);
      E12at = E710t;
      E12as = E710s;
    });
    $('#E82').click(function() {
      $('#E12bt').empty().append(E82t);
      $('#E12bs').empty().append(E82s);
      $('#E14bt').empty();
      $('#E14bs').empty();
      $('#E15bt').empty();
      $('#E15bs').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E12bt').attr('data-teamname', E82t);
      $('#E12bs').attr('data-seed', E82s);
      E12bt = E82t;
      E12bs = E82s;
    });
    $('#E815').click(function() {
      $('#E12bt').empty().append(E815t);
      $('#E12bs').empty().append(E815s);
      $('#E14bt').empty();
      $('#E14bs').empty();
      $('#E15bt').empty();
      $('#E15bs').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E12bt').attr('data-teamname', E815t);
      $('#E12bs').attr('data-seed', E815s);
      E12bt = E815t;
      E12bs = E815s;
    });
    $('#E9a').click(function() {
      $('#E13at').empty().append(E9at);
      $('#E13as').empty().append(E9as);
      $('#E15at').empty();
      $('#E15as').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E13at').attr('data-teamname', E9at);
      $('#E13as').attr('data-seed', E9as);
      E13at = E9at;
      E13as = E9as;
    });
    $('#E9b').click(function() {
      $('#E13at').empty().append(E9bt);
      $('#E13as').empty().append(E9bs);
      $('#E15at').empty();
      $('#E15as').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E13at').attr('data-teamname', E9bt);
      $('#E13as').attr('data-seed', E9bs);
      E13at = E9bt;
      E13as = E9bs;
    });
    $('#E10a').click(function() {
      $('#E13bt').empty().append(E10at);
      $('#E13bs').empty().append(E10as);
      $('#E15at').empty();
      $('#E15as').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E13bt').attr('data-teamname', E10at);
      $('#E13bs').attr('data-seed', E10as);
      E13bt = E10at;
      E13bs = E10as;
    });
    $('#E10b').click(function() {
      $('#E13bt').empty().append(E10bt);
      $('#E13bs').empty().append(E10bs);
      $('#E15at').empty();
      $('#E15as').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E13bt').attr('data-teamname', E10bt);
      $('#E13bs').attr('data-seed', E10bs);
      E13bt = E10bt;
      E13bs = E10bs;
    });
      $('#E11a').click(function() {
      $('#E14at').empty().append(E11at);
      $('#E14as').empty().append(E11as);
      $('#E15bt').empty();
      $('#E15bs').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E14at').attr('data-teamname', E11at);
      $('#E14as').attr('data-seed', E11as);
      E14at = E11at;
      E14as = E11as;
    });
    $('#E11b').click(function() {
      $('#E14at').empty().append(E11bt);
      $('#E14as').empty().append(E11bs);
      $('#E15bt').empty();
      $('#E15bs').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E14at').attr('data-teamname', E11bt);
      $('#E14as').attr('data-seed', E11bs);
      E14at = E11bt;
      E14as = E11bs;
    });
    $('#E12a').click(function() {
      $('#E14bt').empty().append(E12at);
      $('#E14bs').empty().append(E12as);
      $('#E15bt').empty();
      $('#E15bs').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E14bt').attr('data-teamname', E12at);
      $('#E14bs').attr('data-seed', E12as);
      E14bt = E12at;
      E14bs = E12as;
    });
    $('#E12b').click(function() {
      $('#E14bt').empty().append(E12bt);
      $('#E14bs').empty().append(E12bs);
      $('#E15bt').empty();
      $('#E15bs').empty();
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E14bt').attr('data-teamname', E12bt);
      $('#E14bs').attr('data-seed', E12bs);
      E14bt = E12bt;
      E14bs = E12bs;
    });
    $('#E13a').click(function() {
      $('#E15at').empty().append(E13at);
      $('#E15as').empty().append(E13as);
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E15at').attr('data-teamname', E13at);
      $('#E15as').attr('data-seed', E13as);
      E15at = E13at;
      E15as = E13as;
    });
    $('#E13b').click(function() {
      $('#E15at').empty().append(E13bt);
      $('#E15as').empty().append(E13bs);
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E15at').attr('data-teamname', E13bt);
      $('#E15as').attr('data-seed', E13bs);
      E15at = E13bt;
      E15as = E13bs;
    });
    $('#E14a').click(function() {
      $('#E15bt').empty().append(E14at);
      $('#E15bs').empty().append(E14as);
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E15bt').attr('data-teamname', E14at);
      $('#E15bs').attr('data-seed', E14as);
      E15bt = E14at;
      E15bs = E14as;
    });
    $('#E14b').click(function() {
      $('#E15bt').empty().append(E14bt);
      $('#E15bs').empty().append(E14bs);
      $('#FF2bt').empty();
      $('#FF2bs').empty();
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#E15bt').attr('data-teamname', E14bt);
      $('#E15bs').attr('data-seed', E14bs);
      E15bt = E14bt;
      E15bs = E14bs;
    });
    $('#E15a').click(function() {
      $('#FF2bt').empty().append(E15at);
      $('#FF2bs').empty().append(E15as);
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#FF2bt').attr('data-teamname', E15at);
      $('#FF2bs').attr('data-seed', E15as);
      FF2bt = E15at;
      FF2bs = E15as;
    });
    $('#E15b').click(function() {
      $('#FF2bt').empty().append(E15bt);
      $('#FF2bs').empty().append(E15bs);
      $('#FG1bt').empty();
      $('#FG1bs').empty();
      $('#FF2bt').attr('data-teamname', E15bt);
      $('#FF2bs').attr('data-seed', E15bs);
      FF2bt = E15bt;
      FF2bs = E15bs;
    });
  });