  $(document).ready(function() {
    var MW0at = "Play In A"
    var MW0as = "16 "
    var MW0bt = "Play In B"
    var MW0bs = "16 "
    var MW11t = "Option 1";
    var MW11s = "1 ";
    var MW116t = "";
    var MW116s = "";
    var MW28t = "Option 8";
    var MW28s = "8 ";
    var MW29t = "Option 9";
    var MW29s = "9 ";
    var MW35t = "Option 5";
    var MW35s = "5 ";
    var MW312t = "Option 12";
    var MW312s = "12 ";
    var MW44t = "Option 4";
    var MW44s = "4 ";
    var MW413t = "Option 13";
    var MW413s = "13 ";
    var MW56t = "Option 6";
    var MW56s = "6 ";
    var MW511t = "Option 11";
    var MW511s = "11 ";
    var MW63t = "Option 3";
    var MW63s = "3 ";
    var MW614t = "Option 14";
    var MW614s = "14 ";
    var MW77t = "Option 7";
    var MW77s = "7 ";
    var MW710t = "Option 10";
    var MW710s = "10 ";
    var MW82t = "Option 2";
    var MW82s = "2 ";
    var MW815t = "Option 15";
    var MW815s = "15 ";
    var MW9at = "";
    var MW9as = "";
    var MW9bt = "";
    var MW9bs = "";
    var MW10at = "";
    var MW10as = "";
    var MW10bt = "";
    var MW10bs = "";
    var MW11at = "";
    var MW11as = "";
    var MW11bt = "";
    var MW11bs = "";
    var MW12at = "";
    var MW12as = "";
    var MW12bt = "";
    var MW12bs = "";
    $('#MW11t').append(MW11t);
    $('#MW11s').append(MW11s);
    $('#MW0at').append(MW0at);
    $('#MW0as').append(MW0as);
    $('#MW0bt').append(MW0bt);
    $('#MW0bs').append(MW0bs);
    $('#MW28t').append(MW28t);
    $('#MW28s').append(MW28s);
    $('#MW29t').append(MW29t);
    $('#MW29s').append(MW29s);
    $('#MW35t').append(MW35t);
    $('#MW35s').append(MW35s);
    $('#MW312t').append(MW312t);
    $('#MW312s').append(MW312s);
    $('#MW44t').append(MW44t);
    $('#MW44s').append(MW44s);
    $('#MW413t').append(MW413t);
    $('#MW413s').append(MW413s);
    $('#MW56t').append(MW56t);
    $('#MW56s').append(MW56s);
    $('#MW511t').append(MW511t);
    $('#MW511s').append(MW511s);
    $('#MW63t').append(MW63t);
    $('#MW63s').append(MW63s);
    $('#MW614t').append(MW614t);
    $('#MW614s').append(MW614s);
    $('#MW77t').append(MW77t);
    $('#MW77s').append(MW77s);
    $('#MW710t').append(MW710t);
    $('#MW710s').append(MW710s);
    $('#MW82t').append(MW82t);
    $('#MW82s').append(MW82s);
    $('#MW815t').append(MW815t);
    $('#MW815s').append(MW815s);
    $('#MW0a').click(function() {
      $('#MW116t').empty().append(MW0at);
      $('#MW116s').empty().append(MW0as);
      $('#MW9at').empty();
      $('#MW9as').empty();
      $('#MW13at').empty();
      $('#MW13as').empty();
      $('#MW15at').empty();
      $('#MW15as').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW116t').attr('data-teamname', MW0at);
      $('#MW116s').attr('data-seed', MW0as);
      MW116t = MW0at;
      MW116s = MW0as;
    });
    $('#MW0b').click(function() {
      $('#MW116t').empty().append(MW0bt);
      $('#MW116s').empty().append(MW0bs);
      $('#MW9at').empty();
      $('#MW9as').empty();
      $('#MW13at').empty();
      $('#MW13as').empty();
      $('#MW15at').empty();
      $('#MW15as').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW116t').attr('data-teamname', MW0bt);
      $('#MW116s').attr('data-seed', MW0bs);
      MW116t = MW0bt;
      MW116s = MW0bs;
    });
    $('#MW11').click(function() {
      $('#MW9at').empty().append(MW11t);
      $('#MW9as').empty().append(MW11s);
      $('#MW13at').empty();
      $('#MW13as').empty();
      $('#MW15at').empty();
      $('#MW15as').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW9at').attr('data-teamname', MW11t);
      $('#MW9as').attr('data-seed', MW11s);
      MW9at = MW11t;
      MW9as = MW11s;
    });
    $('#MW116').click(function() {
      $('#MW9at').empty().append(MW116t);
      $('#MW9as').empty().append(MW116s);
      $('#MW13at').empty();
      $('#MW13as').empty();
      $('#MW15at').empty();
      $('#MW15as').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW9at').attr('data-teamname', MW116t);
      $('#MW9as').attr('data-seed', MW116s);
      MW9at = MW116t;
      MW9as = MW116s;
    });
    $('#MW28').click(function() {
      $('#MW9bt').empty().append(MW28t);
      $('#MW9bs').empty().append(MW28s);
      $('#MW13at').empty();
      $('#MW13as').empty();
      $('#MW15at').empty();
      $('#MW15as').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW9bt').attr('data-teamname', MW28t);
      $('#MW9bs').attr('data-seed', MW28s);
      MW9bt = MW28t;
      MW9bs = MW28s;
    });
    $('#MW29').click(function() {
      $('#MW9bt').empty().append(MW29t);
      $('#MW9bs').empty().append(MW29s);
      $('#MW13at').empty();
      $('#MW13as').empty();
      $('#MW15at').empty();
      $('#MW15as').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW9bt').attr('data-teamname', MW29t);
      $('#MW9bs').attr('data-seed', MW29s);
      MW9bt = MW29t;
      MW9bs = MW29s;
    });
    $('#MW35').click(function() {
      $('#MW10at').empty().append(MW35t);
      $('#MW10as').empty().append(MW35s);
      $('#MW13bt').empty();
      $('#MW13bs').empty();
      $('#MW15at').empty();
      $('#MW15as').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW10at').attr('data-teamname', MW35t);
      $('#MW10as').attr('data-seed', MW35s);
      MW10at = MW35t;
      MW10as = MW35s;
    });
    $('#MW312').click(function() {
      $('#MW10at').empty().append(MW312t);
      $('#MW10as').empty().append(MW312s);
      $('#MW13bt').empty();
      $('#MW13bs').empty();
      $('#MW15at').empty();
      $('#MW15as').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW10at').attr('data-teamname', MW312t);
      $('#MW10as').attr('data-seed', MW312s);
      MW10at = MW312t;
      MW10as = MW312s;
    });
    $('#MW44').click(function() {
      $('#MW10bt').empty().append(MW44t);
      $('#MW10bs').empty().append(MW44s);
      $('#MW13bt').empty();
      $('#MW13bs').empty();
      $('#MW15at').empty();
      $('#MW15as').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW10bt').attr('data-teamname', MW44t);
      $('#MW10bs').attr('data-seed', MW44s);
      MW10bt = MW44t;
      MW10bs = MW44s;
    });
    $('#MW413').click(function() {
      $('#MW10bt').empty().append(MW413t);
      $('#MW10bs').empty().append(MW413s);
      $('#MW13bt').empty();
      $('#MW13bs').empty();
      $('#MW15at').empty();
      $('#MW15as').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW10bt').attr('data-teamname', MW413t);
      $('#MW10bs').attr('data-seed', MW413s);
      MW10bt = MW413t;
      MW10bs = MW413s;
    });
        $('#MW56').click(function() {
      $('#MW11at').empty().append(MW56t);
      $('#MW11as').empty().append(MW56s);
      $('#MW14at').empty();
      $('#MW14as').empty();
      $('#MW15bt').empty();
      $('#MW15bs').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW11at').attr('data-teamname', MW56t);
      $('#MW11as').attr('data-seed', MW56s);
      MW11at = MW56t;
      MW11as = MW56s;
    });
    $('#MW511').click(function() {
      $('#MW11at').empty().append(MW511t);
      $('#MW11as').empty().append(MW511s);
      $('#MW14at').empty();
      $('#MW14as').empty();
      $('#MW15bt').empty();
      $('#MW15bs').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW11at').attr('data-teamname', MW511t);
      $('#MW11as').attr('data-seed', MW511s);
      MW11at = MW511t;
      MW11as = MW511s;
    });
    $('#MW63').click(function() {
      $('#MW11bt').empty().append(MW63t);
      $('#MW11bs').empty().append(MW63s);
      $('#MW14at').empty();
      $('#MW14as').empty();
      $('#MW15bt').empty();
      $('#MW15bs').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW11bt').attr('data-teamname', MW63t);
      $('#MW11bs').attr('data-seed', MW63s);
      MW11bt = MW63t;
      MW11bs = MW63s;
    });
    $('#MW614').click(function() {
      $('#MW11bt').empty().append(MW614t);
      $('#MW11bs').empty().append(MW614s);
      $('#MW14at').empty();
      $('#MW14as').empty();
      $('#MW15bt').empty();
      $('#MW15bs').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW11bt').attr('data-teamname', MW614t);
      $('#MW11bs').attr('data-seed', MW614s);
      MW11bt = MW614t;
      MW11bs = MW614s;
    });
    $('#MW77').click(function() {
      $('#MW12at').empty().append(MW77t);
      $('#MW12as').empty().append(MW77s);
      $('#MW14bt').empty();
      $('#MW14bs').empty();
      $('#MW15bt').empty();
      $('#MW15bs').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW12at').attr('data-teamname', MW77t);
      $('#MW12as').attr('data-seed', MW77s);
      MW12at = MW77t;
      MW12as = MW77s;
    });
    $('#MW710').click(function() {
      $('#MW12at').empty().append(MW710t);
      $('#MW12as').empty().append(MW710s);
      $('#MW14bt').empty();
      $('#MW14bs').empty();
      $('#MW15bt').empty();
      $('#MW15bs').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW12at').attr('data-teamname', MW710t);
      $('#MW12as').attr('data-seed', MW710s);
      MW12at = MW710t;
      MW12as = MW710s;
    });
    $('#MW82').click(function() {
      $('#MW12bt').empty().append(MW82t);
      $('#MW12bs').empty().append(MW82s);
      $('#MW14bt').empty();
      $('#MW14bs').empty();
      $('#MW15bt').empty();
      $('#MW15bs').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW12bt').attr('data-teamname', MW82t);
      $('#MW12bs').attr('data-seed', MW82s);
      MW12bt = MW82t;
      MW12bs = MW82s;
    });
    $('#MW815').click(function() {
      $('#MW12bt').empty().append(MW815t);
      $('#MW12bs').empty().append(MW815s);
      $('#MW14bt').empty();
      $('#MW14bs').empty();
      $('#MW15bt').empty();
      $('#MW15bs').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW12bt').attr('data-teamname', MW815t);
      $('#MW12bs').attr('data-seed', MW815s);
      MW12bt = MW815t;
      MW12bs = MW815s;
    });
    $('#MW9a').click(function() {
      $('#MW13at').empty().append(MW9at);
      $('#MW13as').empty().append(MW9as);
      $('#MW15at').empty();
      $('#MW15as').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW13at').attr('data-teamname', MW9at);
      $('#MW13as').attr('data-seed', MW9as);
      MW13at = MW9at;
      MW13as = MW9as;
    });
    $('#MW9b').click(function() {
      $('#MW13at').empty().append(MW9bt);
      $('#MW13as').empty().append(MW9bs);
      $('#MW15at').empty();
      $('#MW15as').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW13at').attr('data-teamname', MW9bt);
      $('#MW13as').attr('data-seed', MW9bs);
      MW13at = MW9bt;
      MW13as = MW9bs;
    });
    $('#MW10a').click(function() {
      $('#MW13bt').empty().append(MW10at);
      $('#MW13bs').empty().append(MW10as);
      $('#MW15at').empty();
      $('#MW15as').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW13bt').attr('data-teamname', MW10at);
      $('#MW13bs').attr('data-seed', MW10as);
      MW13bt = MW10at;
      MW13bs = MW10as;
    });
    $('#MW10b').click(function() {
      $('#MW13bt').empty().append(MW10bt);
      $('#MW13bs').empty().append(MW10bs);
      $('#MW15at').empty();
      $('#MW15as').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW13bt').attr('data-teamname', MW10bt);
      $('#MW13bs').attr('data-seed', MW10bs);
      MW13bt = MW10bt;
      MW13bs = MW10bs;
    });
      $('#MW11a').click(function() {
      $('#MW14at').empty().append(MW11at);
      $('#MW14as').empty().append(MW11as);
      $('#MW15bt').empty();
      $('#MW15bs').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW14at').attr('data-teamname', MW11at);
      $('#MW14as').attr('data-seed', MW11as);
      MW14at = MW11at;
      MW14as = MW11as;
    });
    $('#MW11b').click(function() {
      $('#MW14at').empty().append(MW11bt);
      $('#MW14as').empty().append(MW11bs);
      $('#MW15bt').empty();
      $('#MW15bs').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW14at').attr('data-teamname', MW11bt);
      $('#MW14as').attr('data-seed', MW11bs);
      MW14at = MW11bt;
      MW14as = MW11bs;
    });
    $('#MW12a').click(function() {
      $('#MW14bt').empty().append(MW12at);
      $('#MW14bs').empty().append(MW12as);
      $('#MW15bt').empty();
      $('#MW15bs').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW14bt').attr('data-teamname', MW12at);
      $('#MW14bs').attr('data-seed', MW12as);
      MW14bt = MW12at;
      MW14bs = MW12as;
    });
    $('#MW12b').click(function() {
      $('#MW14bt').empty().append(MW12bt);
      $('#MW14bs').empty().append(MW12bs);
      $('#MW15bt').empty();
      $('#MW15bs').empty();
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW14bt').attr('data-teamname', MW12bt);
      $('#MW14bs').attr('data-seed', MW12bs);
      MW14bt = MW12bt;
      MW14bs = MW12bs;
    });
    $('#MW13a').click(function() {
      $('#MW15at').empty().append(MW13at);
      $('#MW15as').empty().append(MW13as);
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW15at').attr('data-teamname', MW13at);
      $('#MW15as').attr('data-seed', MW13as);
      MW15at = MW13at;
      MW15as = MW13as;
    });
    $('#MW13b').click(function() {
      $('#MW15at').empty().append(MW13bt);
      $('#MW15as').empty().append(MW13bs);
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW15at').attr('data-teamname', MW13bt);
      $('#MW15as').attr('data-seed', MW13bs);
      MW15at = MW13bt;
      MW15as = MW13bs;
    });
    $('#MW14a').click(function() {
      $('#MW15bt').empty().append(MW14at);
      $('#MW15bs').empty().append(MW14as);
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW15bt').attr('data-teamname', MW14at);
      $('#MW15bs').attr('data-seed', MW14as);
      MW15bt = MW14at;
      MW15bs = MW14as;
    });
    $('#MW14b').click(function() {
      $('#MW15bt').empty().append(MW14bt);
      $('#MW15bs').empty().append(MW14bs);
      $('#FF1at').empty();
      $('#FF1as').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#MW15bt').attr('data-teamname', MW14bt);
      $('#MW15bs').attr('data-seed', MW14bs);
      MW15bt = MW14bt;
      MW15bs = MW14bs;
    });
    $('#MW15a').click(function() {
      $('#FF1at').empty().append(MW15at);
      $('#FF1as').empty().append(MW15as);
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#FF1at').attr('data-teamname', MW15at);
      $('#FF1as').attr('data-seed', MW15as);
      FF1at = MW15at;
      FF1as = MW15as;
    });
    $('#MW15b').click(function() {
      $('#FF1at').empty().append(MW15bt);
      $('#FF1as').empty().append(MW15bs);
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#FF1at').attr('data-teamname', MW15bt);
      $('#FF1as').attr('data-seed', MW15bs);
      FF1at = MW15bt;
      FF1as = MW15bs;
    });
  });