  $(document).ready(function() {
    var W0at = "";
    var W0as = "";
    var W0bt = "";
    var W0bs = "";
    var W11t = "Oregon";
    var W11s = "1 ";
    var W116t = "Holy Cross";
    var W116s = "16 ";
    var W28t = "ST Joseph's";
    var W28s = "8 ";
    var W29t = "Cincinnati";
    var W29s = "9 ";
    var W35t = "Baylor";
    var W35s = "5 ";
    var W312t = "Yale";
    var W312s = "12 ";
    var W44t = "Duke";
    var W44s = "4 ";
    var W413t = "UNCW";
    var W413s = "13 ";
    var W56t = "Texas";
    var W56s = "6 ";
    var W511t = "Northern Iowa";
    var W511s = "11 ";
    var W63t = "Texas A&M";
    var W63s = "3 ";
    var W614t = "Green bay";
    var W614s = "14 ";
    var W77t = "Oregon State";
    var W77s = "7 ";
    var W710t = "VCU";
    var W710s = "10 ";
    var W82t = "Oklahoma";
    var W82s = "2 ";
    var W815t = "CSU Bakersfield";
    var W815s = "15 ";
    var W9at = "";
    var W9as = "";
    var W9bt = "";
    var W9bs = "";
    var W10at = "";
    var W10as = "";
    var W10bt = "";
    var W10bs = "";
    var W11at = "";
    var W11as = "";
    var W11bt = "";
    var W11bs = "";
    var W12at = "";
    var W12as = "";
    var W12bt = "";
    var W12bs = "";
    $('#W11t').append(W11t);
    $('#W11s').append(W11s);
    $('#W116t').append(W116t);
    $('#W116s').append(W116s);
    $('#W28t').append(W28t);
    $('#W28s').append(W28s);
    $('#W29t').append(W29t);
    $('#W29s').append(W29s);
    $('#W35t').append(W35t);
    $('#W35s').append(W35s);
    $('#W312t').append(W312t);
    $('#W312s').append(W312s);
    $('#W44t').append(W44t);
    $('#W44s').append(W44s);
    $('#W413t').append(W413t);
    $('#W413s').append(W413s);
    $('#W56t').append(W56t);
    $('#W56s').append(W56s);
    $('#W511t').append(W511t);
    $('#W511s').append(W511s);
    $('#W63t').append(W63t);
    $('#W63s').append(W63s);
    $('#W614t').append(W614t);
    $('#W614s').append(W614s);
    $('#W77t').append(W77t);
    $('#W77s').append(W77s);
    $('#W710t').append(W710t);
    $('#W710s').append(W710s);
    $('#W82t').append(W82t);
    $('#W82s').append(W82s);
    $('#W815t').append(W815t);
    $('#W815s').append(W815s);
    $('#W0a').click(function() {
      $('#W116t').empty().append(W0at);
      $('#W116s').empty().append(W0as);
      $('#W9at').empty();
      $('#W9as').empty();
      $('#W13at').empty();
      $('#W13as').empty();
      $('#W15at').empty();
      $('#W15as').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W116t').attr('data-teamname', W0at);
      $('#W116s').attr('data-seed', W0as);
      W116t = W0at;
      W116s = W0as;
    });
    $('#W0b').click(function() {
      $('#W116t').empty().append(W0bt);
      $('#W116s').empty().append(W0bs);
      $('#W9at').empty();
      $('#W9as').empty();
      $('#W13at').empty();
      $('#W13as').empty();
      $('#W15at').empty();
      $('#W15as').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W116t').attr('data-teamname', W0bt);
      $('#W116s').attr('data-seed', W0bs);
      W116t = W0bt;
      W116s = W0bs;
    });
    $('#W11').click(function() {
      $('#W9at').empty().append(W11t);
      $('#W9as').empty().append(W11s);
      $('#W13at').empty();
      $('#W13as').empty();
      $('#W15at').empty();
      $('#W15as').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W9at').attr('data-teamname', W11t);
      $('#W9as').attr('data-seed', W11s);
      W9at = W11t;
      W9as = W11s;
    });
    $('#W116').click(function() {
      $('#W9at').empty().append(W116t);
      $('#W9as').empty().append(W116s);
      $('#W13at').empty();
      $('#W13as').empty();
      $('#W15at').empty();
      $('#W15as').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W9at').attr('data-teamname', W116t);
      $('#W9as').attr('data-seed', W116s);
      W9at = W116t;
      W9as = W116s;
    });
    $('#W28').click(function() {
      $('#W9bt').empty().append(W28t);
      $('#W9bs').empty().append(W28s);
      $('#W13at').empty();
      $('#W13as').empty();
      $('#W15at').empty();
      $('#W15as').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W9bt').attr('data-teamname', W28t);
      $('#W9bs').attr('data-seed', W28s);
      W9bt = W28t;
      W9bs = W28s;
    });
    $('#W29').click(function() {
      $('#W9bt').empty().append(W29t);
      $('#W9bs').empty().append(W29s);
      $('#W13at').empty();
      $('#W13as').empty();
      $('#W15at').empty();
      $('#W15as').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W9bt').attr('data-teamname', W29t);
      $('#W9bs').attr('data-seed', W29s);
      W9bt = W29t;
      W9bs = W29s;
    });
    $('#W35').click(function() {
      $('#W10at').empty().append(W35t);
      $('#W10as').empty().append(W35s);
      $('#W13bt').empty();
      $('#W13bs').empty();
      $('#W15at').empty();
      $('#W15as').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W10at').attr('data-teamname', W35t);
      $('#W10as').attr('data-seed', W35s);
      W10at = W35t;
      W10as = W35s;
    });
    $('#W312').click(function() {
      $('#W10at').empty().append(W312t);
      $('#W10as').empty().append(W312s);
      $('#W13bt').empty();
      $('#W13bs').empty();
      $('#W15at').empty();
      $('#W15as').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W10at').attr('data-teamname', W312t);
      $('#W10as').attr('data-seed', W312s);
      W10at = W312t;
      W10as = W312s;
    });
    $('#W44').click(function() {
      $('#W10bt').empty().append(W44t);
      $('#W10bs').empty().append(W44s);
      $('#W13bt').empty();
      $('#W13bs').empty();
      $('#W15at').empty();
      $('#W15as').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W10bt').attr('data-teamname', W44t);
      $('#W10bs').attr('data-seed', W44s);
      W10bt = W44t;
      W10bs = W44s;
    });
    $('#W413').click(function() {
      $('#W10bt').empty().append(W413t);
      $('#W10bs').empty().append(W413s);
      $('#W13bt').empty();
      $('#W13bs').empty();
      $('#W15at').empty();
      $('#W15as').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W10bt').attr('data-teamname', W413t);
      $('#W10bs').attr('data-seed', W413s);
      W10bt = W413t;
      W10bs = W413s;
    });
        $('#W56').click(function() {
      $('#W11at').empty().append(W56t);
      $('#W11as').empty().append(W56s);
      $('#W14at').empty();
      $('#W14as').empty();
      $('#W15bt').empty();
      $('#W15bs').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W11at').attr('data-teamname', W56t);
      $('#W11as').attr('data-seed', W56s);
      W11at = W56t;
      W11as = W56s;
    });
    $('#W511').click(function() {
      $('#W11at').empty().append(W511t);
      $('#W11as').empty().append(W511s);
      $('#W14at').empty();
      $('#W14as').empty();
      $('#W15bt').empty();
      $('#W15bs').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W11at').attr('data-teamname', W511t);
      $('#W11as').attr('data-seed', W511s);
      W11at = W511t;
      W11as = W511s;
    });
    $('#W63').click(function() {
      $('#W11bt').empty().append(W63t);
      $('#W11bs').empty().append(W63s);
      $('#W14at').empty();
      $('#W14as').empty();
      $('#W15bt').empty();
      $('#W15bs').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W11bt').attr('data-teamname', W63t);
      $('#W11bs').attr('data-seed', W63s);
      W11bt = W63t;
      W11bs = W63s;
    });
    $('#W614').click(function() {
      $('#W11bt').empty().append(W614t);
      $('#W11bs').empty().append(W614s);
      $('#W14at').empty();
      $('#W14as').empty();
      $('#W15bt').empty();
      $('#W15bs').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W11bt').attr('data-teamname', W614t);
      $('#W11bs').attr('data-seed', W614s);
      W11bt = W614t;
      W11bs = W614s;
    });
    $('#W77').click(function() {
      $('#W12at').empty().append(W77t);
      $('#W12as').empty().append(W77s);
      $('#W14bt').empty();
      $('#W14bs').empty();
      $('#W15bt').empty();
      $('#W15bs').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W12at').attr('data-teamname', W77t);
      $('#W12as').attr('data-seed', W77s);
      W12at = W77t;
      W12as = W77s;
    });
    $('#W710').click(function() {
      $('#W12at').empty().append(W710t);
      $('#W12as').empty().append(W710s);
      $('#W14bt').empty();
      $('#W14bs').empty();
      $('#W15bt').empty();
      $('#W15bs').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W12at').attr('data-teamname', W710t);
      $('#W12as').attr('data-seed', W710s);
      W12at = W710t;
      W12as = W710s;
    });
    $('#W82').click(function() {
      $('#W12bt').empty().append(W82t);
      $('#W12bs').empty().append(W82s);
      $('#W14bt').empty();
      $('#W14bs').empty();
      $('#W15bt').empty();
      $('#W15bs').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W12bt').attr('data-teamname', W82t);
      $('#W12bs').attr('data-seed', W82s);
      W12bt = W82t;
      W12bs = W82s;
    });
    $('#W815').click(function() {
      $('#W12bt').empty().append(W815t);
      $('#W12bs').empty().append(W815s);
      $('#W14bt').empty();
      $('#W14bs').empty();
      $('#W15bt').empty();
      $('#W15bs').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W12bt').attr('data-teamname', W815t);
      $('#W12bs').attr('data-seed', W815s);
      W12bt = W815t;
      W12bs = W815s;
    });
    $('#W9a').click(function() {
      $('#W13at').empty().append(W9at);
      $('#W13as').empty().append(W9as);
      $('#W15at').empty();
      $('#W15as').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W13at').attr('data-teamname', W9at);
      $('#W13as').attr('data-seed', W9as);
      W13at = W9at;
      W13as = W9as;
    });
    $('#W9b').click(function() {
      $('#W13at').empty().append(W9bt);
      $('#W13as').empty().append(W9bs);
      $('#W15at').empty();
      $('#W15as').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W13at').attr('data-teamname', W9bt);
      $('#W13as').attr('data-seed', W9bs);
      W13at = W9bt;
      W13as = W9bs;
    });
    $('#W10a').click(function() {
      $('#W13bt').empty().append(W10at);
      $('#W13bs').empty().append(W10as);
      $('#W15at').empty();
      $('#W15as').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W13bt').attr('data-teamname', W10at);
      $('#W13bs').attr('data-seed', W10as);
      W13bt = W10at;
      W13bs = W10as;
    });
    $('#W10b').click(function() {
      $('#W13bt').empty().append(W10bt);
      $('#W13bs').empty().append(W10bs);
      $('#W15at').empty();
      $('#W15as').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W13bt').attr('data-teamname', W10bt);
      $('#W13bs').attr('data-seed', W10bs);
      W13bt = W10bt;
      W13bs = W10bs;
    });
      $('#W11a').click(function() {
      $('#W14at').empty().append(W11at);
      $('#W14as').empty().append(W11as);
      $('#W15bt').empty();
      $('#W15bs').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W14at').attr('data-teamname', W11at);
      $('#W14as').attr('data-seed', W11as);
      W14at = W11at;
      W14as = W11as;
    });
    $('#W11b').click(function() {
      $('#W14at').empty().append(W11bt);
      $('#W14as').empty().append(W11bs);
      $('#W15bt').empty();
      $('#W15bs').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W14at').attr('data-teamname', W11bt);
      $('#W14as').attr('data-seed', W11bs);
      W14at = W11bt;
      W14as = W11bs;
    });
    $('#W12a').click(function() {
      $('#W14bt').empty().append(W12at);
      $('#W14bs').empty().append(W12as);
      $('#W15bt').empty();
      $('#W15bs').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W14bt').attr('data-teamname', W12at);
      $('#W14bs').attr('data-seed', W12as);
      W14bt = W12at;
      W14bs = W12as;
    });
    $('#W12b').click(function() {
      $('#W14bt').empty().append(W12bt);
      $('#W14bs').empty().append(W12bs);
      $('#W15bt').empty();
      $('#W15bs').empty();
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W14bt').attr('data-teamname', W12bt);
      $('#W14bs').attr('data-seed', W12bs);
      W14bt = W12bt;
      W14bs = W12bs;
    });
    $('#W13a').click(function() {
      $('#W15at').empty().append(W13at);
      $('#W15as').empty().append(W13as);
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W15at').attr('data-teamname', W13at);
      $('#W15as').attr('data-seed', W13as);
      W15at = W13at;
      W15as = W13as;
    });
    $('#W13b').click(function() {
      $('#W15at').empty().append(W13bt);
      $('#W15as').empty().append(W13bs);
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W15at').attr('data-teamname', W13bt);
      $('#W15as').attr('data-seed', W13bs);
      W15at = W13bt;
      W15as = W13bs;
    });
    $('#W14a').click(function() {
      $('#W15bt').empty().append(W14at);
      $('#W15bs').empty().append(W14as);
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W15bt').attr('data-teamname', W14at);
      $('#W15bs').attr('data-seed', W14as);
      W15bt = W14at;
      W15bs = W14as;
    });
    $('#W14b').click(function() {
      $('#W15bt').empty().append(W14bt);
      $('#W15bs').empty().append(W14bs);
      $('#FF1bt').empty();
      $('#FF1bs').empty();
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#W15bt').attr('data-teamname', W14bt);
      $('#W15bs').attr('data-seed', W14bs);
      W15bt = W14bt;
      W15bs = W14bs;
    });
    $('#W15a').click(function() {
      $('#FF1bt').empty().append(W15at);
      $('#FF1bs').empty().append(W15as);
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#FF1bt').attr('data-teamname', W15at);
      $('#FF1bs').attr('data-seed', W15as);
      FF1bt = W15at;
      FF1bs = W15as;
    });
    $('#W15b').click(function() {
      $('#FF1bt').empty().append(W15bt);
      $('#FF1bs').empty().append(W15bs);
      $('#FG1at').empty();
      $('#FG1as').empty();
      $('#FF1bt').attr('data-teamname', W15bt);
      $('#FF1bs').attr('data-seed', W15bs);
      FF1bt = W15bt;
      FF1bs = W15bs;
    });
  });